In [84]:
import numpy as np

In [85]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [86]:
a = np.array([[1,2,3,4,5],[12,3,4,5,12]])
print(type(a))
print(a)
print(a.shape)

<class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [12  3  4  5 12]]
(2, 5)


Data Types

In [87]:
a = np.array([[1,23,45,5],[23,21,2,3],[23,21,2,3]],dtype="U2")
print(type(a))
print(a)

<class 'numpy.ndarray'>
[['1' '23' '45' '5']
 ['23' '21' '2' '3']
 ['23' '21' '2' '3']]


In [88]:
print(np.array([[1,23,45,5],[23,21,2,3],[23,21,2,3]],dtype="int64"))

[[ 1 23 45  5]
 [23 21  2  3]
 [23 21  2  3]]


In [89]:
print(np.array([[1,23,45,5],[23,21,2,3],[23,21,2,3]],dtype="int32"))


[[ 1 23 45  5]
 [23 21  2  3]
 [23 21  2  3]]


In [90]:
print(np.array([[1,2,'hello'],[1,2,'hello']],dtype="object"))

[[1 2 'hello']
 [1 2 'hello']]


In [91]:
# signed int8  which can store data between –128 to 127
print(np.array([[1,-120]],dtype="int8"))

[[   1 -120]]


In [92]:
# unsigned int8 which can store data between 0 to 255 (which can store negative values) 

print(np.array([[1,2,3,4,5],[1,2,3,4,5]]))

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [93]:
a = np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(a)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.nbytes)
print(a.itemsize)
print(a[1][1])
print(a[0])
print(a[1:2])
print('|||')
print(a[0::1])
print('|||')


[[1 2 3 4 5]
 [1 2 3 4 5]]
2
(2, 5)
10
int64
80
8
2
[1 2 3 4 5]
[[1 2 3 4 5]]
|||
[[1 2 3 4 5]
 [1 2 3 4 5]]
|||


In [94]:
a = np.array([[21,345,3,34,5],[14,32,3,34,53],[1,45,3,24,5],[1,2,3235,4,5],[1,2,233,44,5],[1,223,43,41,54]])
print(a)
print('||||||||||||')
print(a[1::3])

[[  21  345    3   34    5]
 [  14   32    3   34   53]
 [   1   45    3   24    5]
 [   1    2 3235    4    5]
 [   1    2  233   44    5]
 [   1  223   43   41   54]]
||||||||||||
[[ 14  32   3  34  53]
 [  1   2 233  44   5]]


In [95]:
print(a[1:,1])

[ 32  45   2   2 223]


In [96]:
print(a[:,1:])

[[ 345    3   34    5]
 [  32    3   34   53]
 [  45    3   24    5]
 [   2 3235    4    5]
 [   2  233   44    5]
 [ 223   43   41   54]]


In [97]:
print(a[1:5,1:3])

print(a.shape)

[[  32    3]
 [  45    3]
 [   2 3235]
 [   2  233]]
(6, 5)


In [98]:
a = np.array([[[1,2,3,4],[5,6,7,8]],[[21,21,32,43],[23,12,43,12]]])


# print(a.shape)
# print(a.size)
# print(a.itemsize)
print(a)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[21 21 32 43]
  [23 12 43 12]]]


In [99]:
print(a[1:, : ,1:3])

[[[21 32]
  [12 43]]]


In [100]:
print(a[1,0,2])

32


In [101]:
a = np.array([[1,2,3,4,5,6,7],[10,20,30,40,50,60,70]])

In [102]:
print(a)

[[ 1  2  3  4  5  6  7]
 [10 20 30 40 50 60 70]]


In [103]:
a[1,2] = 300

In [104]:
a

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 10,  20, 300,  40,  50,  60,  70]])

In [105]:
a[1] = [1,1,1,1,1,1,1]

In [106]:
a

array([[1, 2, 3, 4, 5, 6, 7],
       [1, 1, 1, 1, 1, 1, 1]])

In [107]:
a[1] = 90
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [90, 90, 90, 90, 90, 90, 90]])

In [108]:
a[:] = 100
a

array([[100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100]])

In [109]:
a[:,4] = 40
a

array([[100, 100, 100, 100,  40, 100, 100],
       [100, 100, 100, 100,  40, 100, 100]])

In [111]:
a[0:1, 2] = 1000
a

array([[ 100,  100, 1000,  100,   40,  100,  100],
       [ 100,  100,  100,  100,   40,  100,  100]])

In [112]:
a[a>50] = 50000
a

array([[50000, 50000, 50000, 50000,    40, 50000, 50000],
       [50000, 50000, 50000, 50000,    40, 50000, 50000]])

In [113]:
a[a%2==0] = 34
a

array([[34, 34, 34, 34, 34, 34, 34],
       [34, 34, 34, 34, 34, 34, 34]])

In [126]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(a.shape)
print('|||||||')
print(a)




(2, 2, 2)
|||||||
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [129]:
a[1,:] = [[100,300],[223,123]]
print(a)


[[[  1   2]
  [  3   4]]

 [[100 300]
  [223 123]]]
